CREATE DATABASE ProyectoClienteDB;

USE ProyectoClienteDB;

CREATE TABLE cliente(
	idcliente INT PRIMARY KEY NOT NULL, 
    nit NVARCHAR(55) NOT NULL, 
    nombre NVARCHAR(77) NOT NULL, 
    apellido NVARCHAR(77) NOT NULL,
    telefono INT NOT NULL
);

DELIMITER $$
CREATE PROCEDURE `sp_insertarPC_Cliente`(IN pIDCLIENTE INT,IN pNIT NVARCHAR(55),IN pNOMBRE NVARCHAR(77),IN pAPELLIDO NVARCHAR(77),IN pTELEFONO INT)
BEGIN
	INSERT INTO CLIENTE VALUES(pIDCLIENTE,pNIT,pNOMBRE,pAPELLIDO,pTELEFONO);
END
$$

DELIMITER $$
CREATE PROCEDURE `sp_editarPC_Cliente`(IN pIDCLIENTE INT,IN pNIT NVARCHAR(55),IN pNOMBRE NVARCHAR(77),IN pAPELLIDO NVARCHAR(77),IN pTELEFONO INT)
BEGIN
	UPDATE CLIENTE SET NIT=pNIT, NOMBRE = pNOMBRE, APELLIDO = pAPELLIDO, TELEFONO = pTELEFONO WHERE IDCLIENTE = pIDCLIENTE;
END
$$

DELIMITER $$
CREATE PROCEDURE `sp_eliminarPC_Cliente`(IN pIDCLIENTE INT)
BEGIN
	DELETE FROM CLIENTE WHERE IDCLIENTE = pIDCLIENTE;
END
$$